name: publish-cv
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup
        uses: wtfjoke/setup-tectonic@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: build
        run: make all
      - name: release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/*.pdf
          tag_name: "cv_build_${{ github.sha }}"
